name: blogography
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0
  flutter_bloc: ^8.1.6
  go_router: ^14.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  firebase_core: ^3.8.0
  cached_network_image: ^3.4.1
  app_links: ^6.3.2
  simple_ripple_animation: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/globe.svg
    - assets/images/back.svg
