// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBjGunyieNefJikg2zISe1OcdpoXIWBSE',
    appId: '1:299693208700:web:024d53c5ee31d5b31585f9',
    messagingSenderId: '299693208700',
    projectId: 'blogography-e3207',
    authDomain: 'blogography-e3207.firebaseapp.com',
    storageBucket: 'blogography-e3207.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEEz-NrKuBPgmGnAYqTqJt3k_WPwZtEKk',
    appId: '1:299693208700:android:ae291f5fcd50e6681585f9',
    messagingSenderId: '299693208700',
    projectId: 'blogography-e3207',
    storageBucket: 'blogography-e3207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeDvP1gb_FW8eq6UwcJdejJx2QTD8Naic',
    appId: '1:299693208700:ios:929780752b51786a1585f9',
    messagingSenderId: '299693208700',
    projectId: 'blogography-e3207',
    storageBucket: 'blogography-e3207.firebasestorage.app',
    iosBundleId: 'com.example.blogography',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeDvP1gb_FW8eq6UwcJdejJx2QTD8Naic',
    appId: '1:299693208700:ios:929780752b51786a1585f9',
    messagingSenderId: '299693208700',
    projectId: 'blogography-e3207',
    storageBucket: 'blogography-e3207.firebasestorage.app',
    iosBundleId: 'com.example.blogography',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBjGunyieNefJikg2zISe1OcdpoXIWBSE',
    appId: '1:299693208700:web:0c7d17aecdfa25db1585f9',
    messagingSenderId: '299693208700',
    projectId: 'blogography-e3207',
    authDomain: 'blogography-e3207.firebaseapp.com',
    storageBucket: 'blogography-e3207.firebasestorage.app',
  );

}